name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Pages 🏗️
        uses: actions/configure-pages@v1

      - name: Install and Build 🔧
        run: |
          cd app
          npm i
          VITE_BASE=/anpr-ai/ npm run build

      - name: Upload artifact ⬆️
        uses: actions/upload-pages-artifact@v1
        with:
          path: './app/dist'

      - name: Deploy 🚀
        id: deployment
        uses: actions/deploy-pages@main
